spring:
  datasource:
    # 메모리 모드 + MySQL 호환 모드 설정 (중요!)
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  # 웹에서 DB 관리창 켜기
      path: /h2-console  # 접속 주소

  jpa:
    hibernate:
      ddl-auto: create  # 우리가 짠 SQL을 직접 넣을 거니까 자동 생성 끄기
    properties:
      hibernate:
        format_sql: true  # 로그에 SQL 예쁘게 출력
        show_sql: true    # 실행되는 SQL 보여주기